name: e_learning_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  page_transition: ^2.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
